In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('CricketTestMatchData.csv', sep =';')

In [3]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [4]:
#rename Multiple Columns in a list

In [5]:
df = df.rename(columns = {'Mat': 'Matches','NO': 'Not_Outs', 'HS':'Highest_Inns_Score', 'BF': 'Balls_Faced', 'SR': 'Batting_Strike_Rate'})

In [6]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1

In [7]:
#Check Null Values

In [8]:
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced             True
Batting_Strike_Rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [9]:
df[df['Balls_Faced'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11
55,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51+,0

In [10]:
df['Balls_Faced'] = df['Balls_Faced'].fillna('0')

In [11]:
df['Batting_Strike_Rate'] = df['Batting_Strike_Rate'].fillna(0)
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [12]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [13]:
df[df['Player']=='ED Weekes (WI)']

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258+,2

In [14]:
#drop duplicates

In [15]:
df.duplicated()

0     False
1     False
2     False
3     False
4      True
      ...
60    False
61    False
62    False
63    False
64    False
Length: 65, dtype: bool

In [16]:
df[df['Player'].duplicated()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
58,YBK Jaiswal (IND),2023-2026,29,54,2,2535,214*,48.75,3835,66.10,7,13,6,317,45

In [17]:
df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'YBK Jaiswal (IND)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
57,YBK Jaiswal (IND),2023-2026,29,54,2,2535,214*,48.75,3835,66.10,7,13,6,317,45
58,YBK Jaiswal (IND),2023-2026,29,54,2,2535,214*,48.75,3835,66.10,7,13,6,317,45

In [18]:
df = df.drop_duplicates()

In [19]:
df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'YBK Jaiswal (IND)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
57,YBK Jaiswal (IND),2023-2026,29,54,2,2535,214*,48.75,3835,66.10,7,13,6,317,45

In [20]:
# split up span into start and end date

In [21]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2015, 2016]
2     [1963, 1970]
3     [1930, 1954]
5     [1924, 1935]
          ...
60    [1965, 1981]
61    [2002, 2014]
62    [1924, 1934]
63    [1930, 1938]
64    [1928, 1934]
Name: Span, Length: 61, dtype: object

In [22]:
df['Rookie_Year'] = df['Span'].str.split(pat = '-').str[0]

C:\Users\DariaTureac\AppData\Local\Temp\ipykernel_16464\3648638022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rookie_Year'] = df['Span'].str.split(pat = '-').str[0]

In [23]:
df['Final_Year'] = df['Span'].str.split(pat = '-').str[1]

C:\Users\DariaTureac\AppData\Local\Temp\ipykernel_16464\3090471237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Final_Year'] = df['Span'].str.split(pat = '-').str[1]

In [24]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [25]:
# drop Span column

In [26]:
df = df.drop(['Span'], axis =1)

In [27]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935

In [28]:
#Split up the country from the player

In [29]:
df['Player'].str.split(pat = ' ')

0      [DG, Bradman, (AUS)]
1        [AC, Voges, (AUS)]
2       [RG, Pollock, (SA)]
3       [GA, Headley, (WI)]
5     [H, Sutcliffe, (ENG)]
              ...
60     [KD, Walters, (AUS)]
61    [GC, Smith, (ICC/SA)]
62    [WH, Ponsford, (AUS)]
63      [SJ, McCabe, (AUS)]
64     [DR, Jardine, (ENG)]
Name: Player, Length: 61, dtype: object

In [30]:
df['Country'] = df['Player'].str.split(pat = ' ').str[-1].str.strip('()')

In [31]:
df['Player'] = df['Player'].str.split(pat = ' ').str[0] + ' ' + df['Player'].str.split(pat = ' ').str[1]

In [32]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
61,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
62,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
63,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
64,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [33]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
61,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
62,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
63,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
64,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [34]:
# change DataTypes

In [35]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [36]:
df['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     334
1     269
2     274
3     270
5     194
     ...
60    250
61    277
62    266
63    232
64    127
Name: Highest_Inns_Score, Length: 61, dtype: object

In [37]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [38]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].astype('int') # convereted to int

In [39]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [40]:
df = df.astype({'Rookie_Year': 'int', 'Final_Year': 'int'})

In [41]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [42]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG

In [43]:
df['Balls_Faced'] = df['Balls_Faced'].str.split(pat = '+').str[0]

In [44]:
df['Balls_Faced'] = df['Balls_Faced'].astype('int')

In [45]:
df.isnull().any()

Player                 False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
Rookie_Year            False
Final_Year             False
Country                False
dtype: bool

In [46]:
df[df['Balls_Faced'].isna()==1]

Empty DataFrame
Columns: [Player, Matches, Inns, Not_Outs, Runs, Highest_Inns_Score, Ave, Balls_Faced, Batting_Strike_Rate, 100, 50, 0, 4s, 6s, Rookie_Year, Final_Year, Country]
Index: []

In [47]:
pd.set_option('display.max_rows', None)

In [48]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104+,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202+,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125+,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419+,27,1927,1947,ENG
10,PHKD Mendis,16,28,3,1453,182,58.12,2276,63.84,5,6,1,154,25,2022,2026,SL
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593+,32+,1954,1974,WI
13,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
14,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276+,8,1908,1930,ENG
16,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI
17,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358+,7,1937,1955,ENG
18,SPD Smith,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS
19,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
20,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37+,2,1921,1929,ENG
21,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65+,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
23,KS Williamson,110,195,19,9515,251,54.06,18306,51.97,33,38,12,1063,28,2010,2026,NZ
24,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
25,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115+,6,1935,1951,SA
26,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058+,69,1989,2013,IND
27,HC Brook,38,66,2,3395,317,53.04,3910,86.82,10,18,5,369,55,2022,2026,ENG
28,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
29,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788+,48,1976,1993,PAK
30,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
31,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
32,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
33,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
34,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102+,3,1920,1929,AUS
35,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
36,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
37,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
38,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908+,26,1971,1987,IND
39,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
40,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
41,AB de,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
42,JE Root,166,304,25,14114,262,50.58,24534,57.52,41,67,15,1515,46,2012,2026,ENG
43,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
44,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952+,84,1974,1991,WI
45,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342+,3,1937,1957,ENG
46,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
47,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
48,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240+,11,1948,1963,WI
49,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38+,0,1911,1928,ENG
50,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
51,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
52,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
53,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123+,20,1961,1966,SA
54,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41+,1,1929,1949,SA
55,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51+,0,1893,1905,ENG
56,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
57,YBK Jaiswal,29,54,2,2535,214,48.75,3835,66.10,7,13,6,317,45,2023,2026,IND
59,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427+,1,1948,1963,AUS
60,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525+,23,1965,1981,AUS
61,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
62,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119+,0,1924,1934,AUS
63,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241+,5+,1930,1938,AUS
64,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53+,0,1928,1934,ENG

In [49]:
df.isnull().any()

Player                 False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
Rookie_Year            False
Final_Year             False
Country                False
dtype: bool

In [51]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [53]:
df['4s'] = df['4s'].str.split(pat = '+').str[0]

In [54]:
df['4s'] = df['4s'].astype('int')

In [56]:
df['6s'] = df['6s'].str.split(pat = '+').str[0]

In [57]:
df['6s'] = df['6s'].astype('int')

In [58]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [59]:
# Build out Career_Length Column

In [60]:
df['Career_Length'] = df['Final_Year']-df['Rookie_Year']

In [61]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Career_Length
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
2,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA,7
3,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG,11
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG,8
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG,13
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI,10
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG,20
10,PHKD Mendis,16,28,3,1453,182,58.12,2276,63.84,5,6,1,154,25,2022,2026,SL,4
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI,20
13,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,15
14,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG,22
16,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI,12
17,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG,18
18,SPD Smith,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS,16
19,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,18
20,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG,8
21,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI,5
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,2
23,KS Williamson,110,195,19,9515,251,54.06,18306,51.97,33,38,12,1063,28,2010,2026,NZ,16
24,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS,14
25,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA,16
26,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND,24
27,HC Brook,38,66,2,3395,317,53.04,3910,86.82,10,18,5,369,55,2022,2026,ENG,4
28,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,16
29,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK,17
30,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,16
31,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,12
32,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,17
33,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,17
34,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS,9
35,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,10
36,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,8
37,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,21
38,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND,16
39,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,19
40,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,15
41,AB de,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,14
42,JE Root,166,304,25,14114,262,50.58,24534,57.52,41,67,15,1515,46,2012,2026,ENG,14
43,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS,16
44,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI,17
45,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG,20
46,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL,17
47,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK,15
48,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI,15
49,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG,17
50,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND,12
51,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK,2
52,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS,11
53,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA,5
54,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA,20
55,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1893,1905,ENG,12
56,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL,12
57,YBK Jaiswal,29,54,2,2535,214,48.75,3835,66.10,7,13,6,317,45,2023,2026,IND,3
59,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS,15
60,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
61,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
62,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
63,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
64,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [ ]:
# Calculations with the dataframe

In [62]:
# Question 1 -> Cricketers in this DF what is the Average Career Length

In [63]:
df['Career_Length'].mean()

np.float64(13.278688524590164)

In [64]:
# Question 2 -> AVG Batting_Strike_Rate for cricketers who played over 10 years

In [69]:
df[df['Career_Length'] > 10]['Batting_Strike_Rate'].mean()

np.float64(47.8153488372093)

In [70]:
# Question 3 -> find number of cricketers who played before 1960

In [73]:
df[df['Rookie_Year'] < 1960]['Player'].count()

np.int64(23)

In [74]:
# Question 4 -> Max Highest Inns Score by country

In [76]:
df.groupby('Country')['Highest_Inns_Score'].max().to_frame('HighInnCountry').reset_index().sort_values('HighInnCountry', ascending=False)

    Country  HighInnCountry
5    ICC/WI             400
0       AUS             380
10       SL             374
11       WI             365
1       ENG             364
3   ICC/PAK             329
2   ICC/IND             319
8       PAK             313
9        SA             278
4    ICC/SA             277
7        NZ             251
6       IND             248
12      ZIM             232

In [77]:
# Question 5 -> Hundreeds, Fifties, ducks (0) AVG by country

In [79]:
df.groupby('Country')[['100','50','0']].mean()

               100         50          0
Country
AUS      21.600000  29.133333   8.933333
ENG      13.615385  22.153846   4.846154
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      24.000000  32.250000   8.750000
NZ       33.000000  38.000000  12.000000
PAK      21.250000  28.000000   9.500000
SA        9.800000  20.200000   3.400000
SL       22.750000  34.500000   9.500000
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000